from enum import StrEnum


class AnalysisMode(StrEnum):
    NETWORK_ONLY = "NETWORK_ONLY"
    QUEUE_AWARE = "QUEUE_AWARE"


class ServiceClass(StrEnum):
    MANDATORY = "MANDATORY"
    PRIORITY = "PRIORITY"
    BEST_EFFORT = "BEST_EFFORT"


class SegmentationKind(StrEnum):
    ATOMIC_OBJECT = "ATOMIC_OBJECT"
    FIXED_CHUNK = "FIXED_CHUNK"


class StorageMode(StrEnum):
    DISABLED = "DISABLED"
    ENABLED = "ENABLED"


class ReserveEnforcement(StrEnum):
    SOFT = "SOFT"
    HARD = "HARD"


class AdmissionPolicy(StrEnum):
    REJECT_NEW = "REJECT_NEW"


class DependencyKind(StrEnum):
    SEND_AFTER = "SEND_AFTER"


class CapacityProvider(StrEnum):
    FIXED_RATE = "FIXED_RATE"
    FIXED_CAPACITY_PER_CONTACT = "FIXED_CAPACITY_PER_CONTACT"


class RateSemantics(StrEnum):
    CODED_BITRATE = "CODED_BITRATE"
    NET_PAYLOAD_BITRATE_PRE_LOSS = "NET_PAYLOAD_BITRATE_PRE_LOSS"
    APPLICATION_GOODPUT = "APPLICATION_GOODPUT"


class CalculationStatus(StrEnum):
    COMPUTED = "COMPUTED"
    KNOWN_ZERO = "KNOWN_ZERO"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class DecisionGrade(StrEnum):
    VERIFIED = "VERIFIED"
    ENGINEERING_ESTIMATE = "ENGINEERING_ESTIMATE"
    CONCEPT_ONLY = "CONCEPT_ONLY"
    BLOCKED = "BLOCKED"


class EvidenceState(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    PROXY = "PROXY"
    UNKNOWN = "UNKNOWN"


class ValueState(StrEnum):
    KNOWN = "KNOWN"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class PresenceState(StrEnum):
    PROVIDED = "PROVIDED"
    OMITTED = "OMITTED"
    DEFAULTED = "DEFAULTED"


class EvidenceKind(StrEnum):
    MEASURED = "MEASURED"
    MANUFACTURER_PROVIDED = "MANUFACTURER_PROVIDED"
    PUBLIC_SOURCE = "PUBLIC_SOURCE"
    ANALOG_PROXY = "ANALOG_PROXY"
    EXPERT_ESTIMATE = "EXPERT_ESTIMATE"
    USER_ASSUMPTION = "USER_ASSUMPTION"
    SYSTEM_POLICY = "SYSTEM_POLICY"
    DERIVED = "DERIVED"


class OriginKind(StrEnum):
    EXPLICIT = "EXPLICIT"
    PARSED = "PARSED"
    DERIVED = "DERIVED"
    SOURCE_IMPLIED = "SOURCE_IMPLIED"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"


class RunStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"


class ReasonCode(StrEnum):
    GUARD_EXCEEDS_WINDOW = "GUARD_EXCEEDS_WINDOW"
    INPUT_FACTOR_CONFLICT = "INPUT_FACTOR_CONFLICT"
    RATE_UNKNOWN = "RATE_UNKNOWN"
    SESSION_SELECTED_MAX_LOGICAL_BYTES = "SESSION_SELECTED_MAX_LOGICAL_BYTES"
    SESSION_SUPPRESSED_TX_RESOURCE_CONFLICT = "SESSION_SUPPRESSED_TX_RESOURCE_CONFLICT"
    SYNTHETIC_CONTACT_INPUT = "SYNTHETIC_CONTACT_INPUT"
    PAYLOAD_SELECTED_DEADLINE_SEVERITY = "PAYLOAD_SELECTED_DEADLINE_SEVERITY"
    RESERVE_BREACH_SOFT = "RESERVE_BREACH_SOFT"
    ADMISSION_REJECTED_HARD_RESERVE = "ADMISSION_REJECTED_HARD_RESERVE"
    ADMISSION_REJECTED_PHYSICAL_LIMIT = "ADMISSION_REJECTED_PHYSICAL_LIMIT"
    DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
    DEADLINE_MISSED_CONTINUE = "DEADLINE_MISSED_CONTINUE"
    SESSION_SELECTED_MANDATORY_FEASIBILITY = "SESSION_SELECTED_MANDATORY_FEASIBILITY"
    SESSION_SELECTED_POLICY_UTILITY = "SESSION_SELECTED_POLICY_UTILITY"
    SESSION_SELECTED_TIE_BREAK = "SESSION_SELECTED_TIE_BREAK"
    SESSION_SUPPRESSED_LOWER_OBJECTIVE = "SESSION_SUPPRESSED_LOWER_OBJECTIVE"
    PAYLOAD_SELECTED_MANDATORY = "PAYLOAD_SELECTED_MANDATORY"
    DEFERRED_NOT_READY = "DEFERRED_NOT_READY"
    DEFERRED_DEPENDENCY_UNMET = "DEFERRED_DEPENDENCY_UNMET"
    DEFERRED_NO_REMAINING_CAPACITY = "DEFERRED_NO_REMAINING_CAPACITY"
    SPLIT_SESSION_CAPACITY = "SPLIT_SESSION_CAPACITY"
    SPLIT_FIXED_CHUNK_BOUNDARY = "SPLIT_FIXED_CHUNK_BOUNDARY"
    RESUME_NEXT_SESSION = "RESUME_NEXT_SESSION"
    NOT_STARTED_ATOMIC_NOT_COMPLETABLE = "NOT_STARTED_ATOMIC_NOT_COMPLETABLE"
    NOT_STARTED_KNOWN_ZERO_SESSION = "NOT_STARTED_KNOWN_ZERO_SESSION"
    EXPIRED_BEFORE_START = "EXPIRED_BEFORE_START"
    EXPIRED_AFTER_PARTIAL = "EXPIRED_AFTER_PARTIAL"
    RELEASE_HELD_INCOMPLETE_OBJECT = "RELEASE_HELD_INCOMPLETE_OBJECT"
    RELEASE_HELD_WAITING_EVENT = "RELEASE_HELD_WAITING_EVENT"
    RELEASED_TX_END_PROXY = "RELEASED_TX_END_PROXY"
    RELEASED_ON_ACK = "RELEASED_ON_ACK"
    OBJECT_GENERATED_AT_READY = "OBJECT_GENERATED_AT_READY"
    BUNDLE_ACTIONABLE_REQUIRED_MEMBERS_COMPLETE = "BUNDLE_ACTIONABLE_REQUIRED_MEMBERS_COMPLETE"
    BUNDLE_DEGRADED_OPTIONAL_MISSING = "BUNDLE_DEGRADED_OPTIONAL_MISSING"
    BUNDLE_UNACHIEVABLE_REQUIRED_MISSING = "BUNDLE_UNACHIEVABLE_REQUIRED_MISSING"


class WarningCode(StrEnum):
    NOT_A_COMMAND_PLAN = "NOT_A_COMMAND_PLAN"
    NOT_A_GROUND_STATION_RESERVATION = "NOT_A_GROUND_STATION_RESERVATION"
    NOT_GROUND_VERIFIED = "NOT_GROUND_VERIFIED"
    NO_OPERATIONS_ELIGIBILITY_DECISION = "NO_OPERATIONS_ELIGIBILITY_DECISION"
    PROXY_DEPENDENT_RESULT = "PROXY_DEPENDENT_RESULT"
    UNMODELED_PHYSICAL_CONSTRAINTS = "UNMODELED_PHYSICAL_CONSTRAINTS"
    SYNTHETIC_TEST_DELIVERY_EVENTS_ONLY = "SYNTHETIC_TEST_DELIVERY_EVENTS_ONLY"
    ASSUMED_DELIVERY_PROXY_RESULT = "ASSUMED_DELIVERY_PROXY_RESULT"
    NOT_GLOBALLY_OPTIMAL = "NOT_GLOBALLY_OPTIMAL"


#: Warnings that every P0 result carries. Conditional warnings are appended by the run.
SAFETY_WARNING_CODES: tuple[WarningCode, ...] = (
    WarningCode.NOT_A_COMMAND_PLAN,
    WarningCode.NOT_A_GROUND_STATION_RESERVATION,
    WarningCode.NOT_GROUND_VERIFIED,
    WarningCode.NO_OPERATIONS_ELIGIBILITY_DECISION,
    WarningCode.PROXY_DEPENDENT_RESULT,
    WarningCode.UNMODELED_PHYSICAL_CONSTRAINTS,
)


class ExecutionStrategy(StrEnum):
    """How `QUEUE_AWARE` resolves overlapping opportunities. A semantic input, never a knob.

    It changes what the result *means*, so it is part of the canonical input, the result, the
    provenance and every hash. `EXACT_GLOBAL` is the default and the only mode that establishes
    optimality. `BOUNDED_APPROXIMATE` must be chosen deliberately: an exact search that exceeds
    its budget fails by name and never falls back to this on its own.
    """

    EXACT_GLOBAL = "EXACT_GLOBAL"
    BOUNDED_APPROXIMATE = "BOUNDED_APPROXIMATE"


class OptimizationStatus(StrEnum):
    """What the run established about the selection, as opposed to what was asked for."""

    EXACT = "EXACT"
    APPROXIMATE = "APPROXIMATE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ComparisonReasonCode(StrEnum):
    METRIC_NOT_COMPUTED_IN_BOTH_RUNS = "METRIC_NOT_COMPUTED_IN_BOTH_RUNS"
    METRIC_DEFINITION_MISMATCH = "METRIC_DEFINITION_MISMATCH"
    METRIC_UNIT_MISMATCH = "METRIC_UNIT_MISMATCH"
    METRIC_ACCOUNTING_LAYER_MISMATCH = "METRIC_ACCOUNTING_LAYER_MISMATCH"
    METRIC_SCHEMA_REVISION_MISMATCH = "METRIC_SCHEMA_REVISION_MISMATCH"
    BASELINE_ZERO_RATIO_UNDEFINED = "BASELINE_ZERO_RATIO_UNDEFINED"
    #: v1.4 golden-design name; EVIDENCE_GRADE_MISMATCH is the P0 spec alias. Both are emitted.
    COMPARABLE_WITH_EVIDENCE_DIFFERENCE = "COMPARABLE_WITH_EVIDENCE_DIFFERENCE"
    EVIDENCE_GRADE_MISMATCH = "EVIDENCE_GRADE_MISMATCH"
    #: One side established optimality and the other did not; the numbers are not like for like.
    OPTIMIZATION_GRADE_MISMATCH = "OPTIMIZATION_GRADE_MISMATCH"


class RateScope(StrEnum):
    ACTIVE_DATA_WINDOW = "ACTIVE_DATA_WINDOW"
    WHOLE_MODELED_CONTACT = "WHOLE_MODELED_CONTACT"


class AccountedEffect(StrEnum):
    CODING = "CODING"
    PROTOCOL_OVERHEAD = "PROTOCOL_OVERHEAD"
    RESIDUAL_LOSS = "RESIDUAL_LOSS"
    RETRANSMISSION = "RETRANSMISSION"
    FEC = "FEC"
    PADDING = "PADDING"


class ProducerKind(StrEnum):
    MODEL_DERIVED = "MODEL_DERIVED"
    USER_SUPPLIED = "USER_SUPPLIED"


class ProfileKind(StrEnum):
    SPACECRAFT = "SPACECRAFT"
    ORBIT = "ORBIT"
    GROUND_STATION = "GROUND_STATION"
    COMMUNICATION = "COMMUNICATION"
    PAYLOAD_TYPE = "PAYLOAD_TYPE"
    POLICY = "POLICY"


class RevisionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"


class PolicyKind(StrEnum):
    DEADLINE_SEVERITY = "DEADLINE_SEVERITY"


class ContactSource(StrEnum):
    """Provenance of a contact interval. See ADR-0002."""

    ORBIT_DERIVED = "ORBIT_DERIVED"
    SYNTHETIC_INJECTED = "SYNTHETIC_INJECTED"


class OrbitKind(StrEnum):
    """Which supported orbit assumption an ``ORBIT_DERIVED`` scenario carries.

    Both are propagated by the pure-Python engine behind the ``ContactProvider`` port; neither
    describes a real KMU-ET02 orbit. ``GP_TLE`` propagates a user-supplied two-line element set
    with SGP4; ``TWO_BODY_V1`` propagates literal Keplerian elements under point-mass gravity.
    See ADR-0004 and ``docs/specs/ORBIT_VERIFICATION_CONTRACT.md``.
    """

    GP_TLE = "GP_TLE"
    TWO_BODY_V1 = "TWO_BODY_V1"


class ReleaseTrigger(StrEnum):
    NEVER = "NEVER"
    TX_END = "TX_END"
    ACKED = "ACKED"


class DeliveryAssumption(StrEnum):
    NONE = "NONE"
    TX_END_EQUALS_DELIVERED = "TX_END_EQUALS_DELIVERED"


class ReclaimGranularity(StrEnum):
    OBJECT = "OBJECT"


class DeliveryConfirmationState(StrEnum):
    NOT_OBSERVED = "NOT_OBSERVED"
    ASSUMED = "ASSUMED"


class EventOrigin(StrEnum):
    """Only TEST_SYNTHETIC exists in P0. Real ground events are P2."""

    TEST_SYNTHETIC = "TEST_SYNTHETIC"


class BundleMemberRole(StrEnum):
    REQUIRED_ACTIONABLE = "REQUIRED_ACTIONABLE"
    REQUIRED_COMPLETE = "REQUIRED_COMPLETE"
    OPTIONAL = "OPTIONAL"


class DeadlineTarget(StrEnum):
    INSTANCE_COMPLETE = "INSTANCE_COMPLETE"


class PostDeadlineAction(StrEnum):
    CONTINUE_AND_REPORT = "CONTINUE_AND_REPORT"


class TransferStartPolicy(StrEnum):
    ONLY_IF_COMPLETABLE = "ONLY_IF_COMPLETABLE"


class BundleStatus(StrEnum):
    ACHIEVED = "ACHIEVED"
    DEGRADED = "DEGRADED"
    UNACHIEVABLE = "UNACHIEVABLE"
    PENDING = "PENDING"


class EventDomain(StrEnum):
    QUEUE = "QUEUE"
    STORAGE = "STORAGE"


class EventKind(StrEnum):
    ALLOCATION_OPEN = "ALLOCATION_OPEN"
    ALLOCATION_CLOSE = "ALLOCATION_CLOSE"
    MODELED_TX_PROGRESS_AT_TX_END = "MODELED_TX_PROGRESS_AT_TX_END"
    TEST_DELIVERY_INGESTED = "TEST_DELIVERY_INGESTED"
    OBJECT_RELEASED = "OBJECT_RELEASED"
    RELEASE_HELD = "RELEASE_HELD"
    OBJECT_GENERATED = "OBJECT_GENERATED"
    OBJECT_ADMITTED = "OBJECT_ADMITTED"
    OBJECT_REJECTED = "OBJECT_REJECTED"
