-- SEMANTIX PassBudget local SQLite schema v1
-- Applied by src/semantix_passbudget/adapters/sqlite/schema.py. Rationale, the exact-integer
-- representation decision and the divergences from the PostgreSQL schema are in
-- docs/architecture/ADR-0003-persistence-tiers.md.
--
-- Representation contract
--   * exact integers (bytes, counts, offsets) are canonical decimal TEXT, never INTEGER.
--     SQLite INTEGER is signed 64-bit (max 9,223,372,036,854,775,807) while the accepted
--     PostgreSQL columns are numeric(20,0) (max 10^20-1) and numeric(39,0) (max 10^39-1),
--     so INTEGER would silently truncate or coerce to float at the top of the domain.
--   * timestamps are INTEGER UTC epoch microseconds. Year 9999 is 253402300799999999 us,
--     which fits int64 with four orders of magnitude to spare.
--   * SHA-256 digests are lowercase hex TEXT of exactly 64 characters.
--   * UUIDs are generated by the application, never by a database default.
--   * enums are TEXT NOT NULL CHECK (col IN (...)) mirroring the code enum exactly.
--
-- Secrets, host addresses, personal paths and fixture data are intentionally absent.

CREATE TABLE schema_version (
  id                INTEGER PRIMARY KEY CHECK (id = 1),
  version           INTEGER NOT NULL,
  applied_at_us     INTEGER NOT NULL
);

-- 1. Scenario head. Mutable name/archive only; identity is immutable.
CREATE TABLE scenario (
  id                TEXT PRIMARY KEY,
  stable_key        TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  description       TEXT,
  is_preset         INTEGER NOT NULL CHECK (is_preset IN (0, 1)),
  created_at_us     INTEGER NOT NULL,
  CONSTRAINT scenario_stable_key_ck CHECK (
    length(stable_key) BETWEEN 1 AND 64
    AND NOT stable_key GLOB '*[^A-Za-z0-9._:-]*'
  )
);

-- 2. Immutable scenario revision. The contact-source contract of ADR-0002 is enforced here too:
-- a synthetic revision may not carry an orbit revision, and an orbit revision must carry one.
CREATE TABLE scenario_revision (
  id                                   TEXT PRIMARY KEY,
  scenario_id                          TEXT NOT NULL REFERENCES scenario(id) ON DELETE RESTRICT,
  revision_no                          INTEGER NOT NULL CHECK (revision_no > 0),
  lifecycle_status                     TEXT NOT NULL CHECK (lifecycle_status IN ('DRAFT', 'PUBLISHED')),
  schema_version                       TEXT NOT NULL,
  decision_question                    TEXT NOT NULL,
  analysis_start_us                    INTEGER NOT NULL,
  analysis_end_us                      INTEGER NOT NULL,
  analysis_mode                        TEXT NOT NULL CHECK (analysis_mode IN ('NETWORK_ONLY', 'QUEUE_AWARE')),
  contact_source                       TEXT NOT NULL CHECK (contact_source IN ('ORBIT_DERIVED', 'SYNTHETIC_INJECTED')),
  synthetic_contact_provider_revision  TEXT,
  orbit_revision_id                    TEXT,
  policy_revision_key                  TEXT,
  spacecraft_key                       TEXT NOT NULL,
  storage_mode                         TEXT NOT NULL CHECK (storage_mode IN ('DISABLED', 'ENABLED')),
  physical_capacity_bytes              TEXT,
  protected_reserve_bytes              TEXT,
  initial_nonqueue_bytes               TEXT,
  reserve_enforcement                  TEXT CHECK (reserve_enforcement IS NULL OR reserve_enforcement IN ('HARD', 'SOFT')),
  storage_admission_policy             TEXT CHECK (storage_admission_policy IS NULL OR storage_admission_policy = 'REJECT_NEW'),
  reclaim_granularity                  TEXT CHECK (reclaim_granularity IS NULL OR reclaim_granularity IN ('OBJECT', 'CHUNK')),
  release_trigger                      TEXT CHECK (release_trigger IS NULL OR release_trigger IN ('NEVER', 'TX_END', 'ACKED')),
  delivery_assumption                  TEXT CHECK (delivery_assumption IS NULL OR delivery_assumption IN ('NONE', 'TX_END_EQUALS_DELIVERED')),
  overlap_objective_revision           TEXT NOT NULL,
  tie_break_profile_revision           TEXT NOT NULL,
  event_order_revision                 TEXT NOT NULL,
  time_quantization_revision           TEXT NOT NULL,
  display_format_revision              TEXT NOT NULL,
  semantic_hash                        TEXT NOT NULL CHECK (length(semantic_hash) = 64),
  published_at_us                      INTEGER,
  UNIQUE (scenario_id, revision_no),
  UNIQUE (scenario_id, semantic_hash),
  CONSTRAINT scenario_revision_interval_ck CHECK (analysis_start_us < analysis_end_us),
  CONSTRAINT scenario_revision_contact_source_ck CHECK (
    (contact_source = 'ORBIT_DERIVED'
      AND orbit_revision_id IS NOT NULL
      AND synthetic_contact_provider_revision IS NULL)
    OR
    (contact_source = 'SYNTHETIC_INJECTED'
      AND orbit_revision_id IS NULL
      AND synthetic_contact_provider_revision IS NOT NULL)
  ),
  CONSTRAINT scenario_revision_mode_ck CHECK (
    (analysis_mode = 'NETWORK_ONLY' AND policy_revision_key IS NULL AND storage_mode = 'DISABLED')
    OR analysis_mode = 'QUEUE_AWARE'
  ),
  CONSTRAINT scenario_revision_storage_ck CHECK (
    (storage_mode = 'DISABLED'
      AND physical_capacity_bytes IS NULL AND protected_reserve_bytes IS NULL
      AND initial_nonqueue_bytes IS NULL AND reserve_enforcement IS NULL
      AND storage_admission_policy IS NULL AND reclaim_granularity IS NULL
      AND release_trigger IS NULL AND delivery_assumption IS NULL)
    OR
    (storage_mode = 'ENABLED' AND analysis_mode = 'QUEUE_AWARE'
      AND physical_capacity_bytes IS NOT NULL AND protected_reserve_bytes IS NOT NULL
      AND initial_nonqueue_bytes IS NOT NULL AND reserve_enforcement IS NOT NULL
      AND storage_admission_policy IS NOT NULL AND reclaim_granularity IS NOT NULL
      AND release_trigger IS NOT NULL AND delivery_assumption IS NOT NULL)
  ),
  CONSTRAINT scenario_revision_exact_bytes_ck CHECK (
    (physical_capacity_bytes IS NULL OR NOT physical_capacity_bytes GLOB '*[^0-9]*')
    AND (protected_reserve_bytes IS NULL OR NOT protected_reserve_bytes GLOB '*[^0-9]*')
    AND (initial_nonqueue_bytes IS NULL OR NOT initial_nonqueue_bytes GLOB '*[^0-9]*')
  )
);

-- 3. Scenario station binding. The discriminator is mirrored so a station row cannot disagree
-- with its revision, matching the composite-FK chain of the PostgreSQL v0.2 delta.
CREATE TABLE scenario_station (
  id                       TEXT PRIMARY KEY,
  scenario_revision_id     TEXT NOT NULL REFERENCES scenario_revision(id) ON DELETE RESTRICT,
  stable_key               TEXT NOT NULL,
  station_preference_rank  INTEGER NOT NULL CHECK (station_preference_rank >= 0),
  minimum_elevation_udeg   INTEGER CHECK (
    minimum_elevation_udeg IS NULL
    OR (minimum_elevation_udeg >= 0 AND minimum_elevation_udeg < 90000000)
  ),
  link_compatibility       TEXT NOT NULL CHECK (link_compatibility IN ('ELIGIBLE', 'INELIGIBLE', 'UNKNOWN')),
  contact_source           TEXT NOT NULL CHECK (contact_source IN ('ORBIT_DERIVED', 'SYNTHETIC_INJECTED')),
  communication_key        TEXT NOT NULL,
  ground_station_key       TEXT NOT NULL,
  UNIQUE (scenario_revision_id, stable_key)
);

-- 4. Communication contract per station. The rate timeline is repeated typed rows, never a blob.
CREATE TABLE communication_revision (
  id                        TEXT PRIMARY KEY,
  scenario_revision_id      TEXT NOT NULL REFERENCES scenario_revision(id) ON DELETE RESTRICT,
  stable_key                TEXT NOT NULL,
  provider_kind             TEXT NOT NULL CHECK (provider_kind IN ('FIXED_RATE', 'FIXED_CAPACITY_PER_CONTACT')),
  fixed_capacity_bytes      TEXT CHECK (fixed_capacity_bytes IS NULL OR NOT fixed_capacity_bytes GLOB '*[^0-9]*'),
  rate_semantics            TEXT CHECK (
    rate_semantics IS NULL
    OR rate_semantics IN ('CODED_BITRATE', 'NET_PAYLOAD_BITRATE_PRE_LOSS', 'APPLICATION_GOODPUT')
  ),
  measurement_point         TEXT,
  rate_scope                TEXT CHECK (rate_scope IS NULL OR rate_scope IN ('ACTIVE_DATA_WINDOW', 'WHOLE_MODELED_CONTACT')),
  accounted_effects         TEXT NOT NULL,
  acquisition_guard_us      INTEGER NOT NULL CHECK (acquisition_guard_us >= 0),
  release_guard_us          INTEGER NOT NULL CHECK (release_guard_us >= 0),
  reserve_kind              TEXT NOT NULL CHECK (reserve_kind IN ('NONE', 'BYTE', 'TIME')),
  reserve_bytes             TEXT CHECK (reserve_bytes IS NULL OR NOT reserve_bytes GLOB '*[^0-9]*'),
  capacity_accounting_layer TEXT NOT NULL CHECK (capacity_accounting_layer = 'LOGICAL_PAYLOAD'),
  rate_unknown              INTEGER NOT NULL CHECK (rate_unknown IN (0, 1)),
  evidence_state            TEXT NOT NULL CHECK (evidence_state IN ('CONFIRMED', 'PROVISIONAL', 'PROXY', 'UNKNOWN')),
  source_revision_id        TEXT,
  rationale                 TEXT,
  UNIQUE (scenario_revision_id, stable_key),
  CONSTRAINT communication_provider_ck CHECK (
    (provider_kind = 'FIXED_RATE' AND fixed_capacity_bytes IS NULL)
    OR (provider_kind = 'FIXED_CAPACITY_PER_CONTACT'
        AND rate_semantics IS NULL AND measurement_point IS NULL AND rate_scope IS NULL)
  )
);

-- 5. Exact rate and time-reserve segments relative to the active-data interval.
CREATE TABLE communication_timeline_segment (
  communication_revision_id TEXT NOT NULL REFERENCES communication_revision(id) ON DELETE RESTRICT,
  segment_kind              TEXT NOT NULL CHECK (segment_kind IN ('RATE', 'TIME_RESERVE')),
  ordinal                   INTEGER NOT NULL CHECK (ordinal >= 0),
  start_offset_us           INTEGER NOT NULL CHECK (start_offset_us >= 0),
  end_offset_us             INTEGER,
  rate_numerator_bits       TEXT CHECK (rate_numerator_bits IS NULL OR NOT rate_numerator_bits GLOB '*[^0-9]*'),
  rate_denominator_seconds  TEXT CHECK (rate_denominator_seconds IS NULL OR NOT rate_denominator_seconds GLOB '*[^0-9]*'),
  PRIMARY KEY (communication_revision_id, segment_kind, ordinal),
  CONSTRAINT segment_shape_ck CHECK (
    (segment_kind = 'RATE'
      AND (end_offset_us IS NULL OR start_offset_us < end_offset_us)
      AND rate_numerator_bits IS NOT NULL AND rate_denominator_seconds IS NOT NULL)
    OR
    (segment_kind = 'TIME_RESERVE'
      AND end_offset_us IS NOT NULL AND start_offset_us < end_offset_us
      AND rate_numerator_bits IS NULL AND rate_denominator_seconds IS NULL)
  )
);

-- 6. Explicit payload instance for QUEUE_AWARE scenarios.
CREATE TABLE scenario_payload (
  id                       TEXT PRIMARY KEY,
  scenario_revision_id     TEXT NOT NULL REFERENCES scenario_revision(id) ON DELETE RESTRICT,
  stable_key               TEXT NOT NULL,
  payload_type_key         TEXT NOT NULL,
  display_name             TEXT NOT NULL,
  media_type               TEXT NOT NULL,
  producer_kind            TEXT NOT NULL CHECK (producer_kind IN ('MODEL_DERIVED', 'USER_SUPPLIED')),
  ready_at_us              INTEGER NOT NULL,
  logical_size_bytes       TEXT NOT NULL CHECK (NOT logical_size_bytes GLOB '*[^0-9]*'),
  storage_footprint_bytes  TEXT NOT NULL CHECK (NOT storage_footprint_bytes GLOB '*[^0-9]*'),
  service_class            TEXT NOT NULL CHECK (service_class IN ('MANDATORY', 'PRIORITY', 'BEST_EFFORT')),
  mission_priority         INTEGER NOT NULL CHECK (mission_priority BETWEEN 0 AND 100),
  queue_sequence           INTEGER NOT NULL CHECK (queue_sequence >= 0),
  deadline_at_us           INTEGER,
  deadline_target          TEXT CHECK (deadline_target IS NULL OR deadline_target = 'INSTANCE_COMPLETE'),
  post_deadline_action     TEXT CHECK (post_deadline_action IS NULL OR post_deadline_action = 'CONTINUE_AND_REPORT'),
  expiry_at_us             INTEGER,
  severity_rank            INTEGER CHECK (severity_rank IS NULL OR severity_rank BETWEEN 0 AND 100),
  segmentation             TEXT NOT NULL CHECK (segmentation IN ('ATOMIC_OBJECT', 'FIXED_CHUNK')),
  chunk_size_bytes         TEXT CHECK (chunk_size_bytes IS NULL OR NOT chunk_size_bytes GLOB '*[^0-9]*'),
  resume_supported         INTEGER NOT NULL CHECK (resume_supported IN (0, 1)),
  bundle_key               TEXT,
  bundle_member_role       TEXT CHECK (
    bundle_member_role IS NULL
    OR bundle_member_role IN ('REQUIRED_ACTIONABLE', 'REQUIRED_COMPLETE', 'OPTIONAL')
  ),
  initial_storage_state    TEXT NOT NULL CHECK (initial_storage_state IN ('GENERATED_AT_READY', 'ALREADY_STORED')),
  UNIQUE (scenario_revision_id, stable_key),
  UNIQUE (scenario_revision_id, queue_sequence),
  CONSTRAINT payload_deadline_ck CHECK (
    (deadline_at_us IS NULL AND deadline_target IS NULL AND post_deadline_action IS NULL)
    OR (deadline_at_us IS NOT NULL AND deadline_target IS NOT NULL AND post_deadline_action IS NOT NULL)
  ),
  CONSTRAINT payload_expiry_ck CHECK (expiry_at_us IS NULL OR ready_at_us < expiry_at_us),
  CONSTRAINT payload_bundle_ck CHECK (
    (bundle_key IS NULL AND bundle_member_role IS NULL)
    OR (bundle_key IS NOT NULL AND bundle_member_role IS NOT NULL)
  ),
  CONSTRAINT payload_chunk_ck CHECK (
    (segmentation = 'FIXED_CHUNK' AND chunk_size_bytes IS NOT NULL AND resume_supported = 1)
    OR (segmentation = 'ATOMIC_OBJECT' AND chunk_size_bytes IS NULL AND resume_supported = 0)
  )
);

-- 7. Repeated dependency edges. Cycle detection is a service invariant, not a table constraint.
CREATE TABLE payload_dependency (
  scenario_revision_id    TEXT NOT NULL REFERENCES scenario_revision(id) ON DELETE RESTRICT,
  predecessor_payload_id  TEXT NOT NULL REFERENCES scenario_payload(id) ON DELETE RESTRICT,
  successor_payload_id    TEXT NOT NULL REFERENCES scenario_payload(id) ON DELETE RESTRICT,
  dependency_kind         TEXT NOT NULL,
  PRIMARY KEY (scenario_revision_id, predecessor_payload_id, successor_payload_id, dependency_kind),
  CONSTRAINT payload_dependency_self_ck CHECK (predecessor_payload_id <> successor_payload_id)
);

-- 8. Immutable calculator/environment contract.
CREATE TABLE engine_manifest (
  id                        TEXT PRIMARY KEY,
  stable_key                TEXT NOT NULL UNIQUE,
  engine_version            TEXT NOT NULL,
  code_revision             TEXT NOT NULL,
  orbit_provider_revision   TEXT NOT NULL,
  capacity_engine_revision  TEXT NOT NULL,
  scheduler_revision        TEXT NOT NULL,
  storage_reducer_revision  TEXT NOT NULL,
  constants_revision        TEXT NOT NULL,
  time_reference_revision   TEXT NOT NULL,
  frame_transform_revision  TEXT NOT NULL,
  event_solver_revision     TEXT NOT NULL,
  canonicalization_revision TEXT NOT NULL,
  manifest_sha256           TEXT NOT NULL CHECK (length(manifest_sha256) = 64)
);

-- 9. Immutable, self-contained input artifact. canonical_bytes is authoritative for the hash;
-- canonical_payload is a schema-validated inspection copy and never replaces the typed rows.
CREATE TABLE input_snapshot (
  id                        TEXT PRIMARY KEY,
  scenario_revision_id      TEXT NOT NULL REFERENCES scenario_revision(id) ON DELETE RESTRICT,
  schema_version            TEXT NOT NULL,
  json_schema_id            TEXT NOT NULL,
  canonicalization_revision TEXT NOT NULL,
  canonical_payload         TEXT NOT NULL,
  canonical_bytes           BLOB NOT NULL,
  content_sha256            TEXT NOT NULL CHECK (length(content_sha256) = 64),
  validation_status         TEXT NOT NULL CHECK (validation_status IN ('VALID', 'INVALID')),
  validation_code           TEXT,
  created_at_us             INTEGER NOT NULL,
  UNIQUE (content_sha256, canonicalization_revision),
  CONSTRAINT input_snapshot_validation_ck CHECK (
    (validation_status = 'VALID' AND validation_code IS NULL)
    OR (validation_status = 'INVALID' AND validation_code IS NOT NULL)
  )
);

-- 10. Run identity and terminal state. Terminal rows are immutable (trigger below).
CREATE TABLE scenario_run (
  id                   TEXT PRIMARY KEY,
  input_snapshot_id    TEXT NOT NULL REFERENCES input_snapshot(id) ON DELETE RESTRICT,
  engine_manifest_id   TEXT NOT NULL REFERENCES engine_manifest(id) ON DELETE RESTRICT,
  replay_of_run_id     TEXT REFERENCES scenario_run(id) ON DELETE RESTRICT,
  status               TEXT NOT NULL CHECK (status IN ('SUCCEEDED', 'PARTIAL', 'FAILED', 'INVALID')),
  retention_class      TEXT NOT NULL CHECK (retention_class IN ('STANDARD', 'BASELINE')),
  requested_at_us      INTEGER NOT NULL,
  started_at_us        INTEGER NOT NULL,
  finished_at_us       INTEGER NOT NULL,
  terminal_stage_code  TEXT NOT NULL,
  error_code           TEXT,
  result_content_hash  TEXT NOT NULL CHECK (length(result_content_hash) = 64),
  run_record_hash      TEXT NOT NULL CHECK (length(run_record_hash) = 64),
  CONSTRAINT scenario_run_time_ck CHECK (
    requested_at_us <= started_at_us AND started_at_us <= finished_at_us
  )
);

-- 11. Per-stage state preserves partial successes.
CREATE TABLE run_stage (
  id                  TEXT PRIMARY KEY,
  run_id              TEXT NOT NULL REFERENCES scenario_run(id) ON DELETE RESTRICT,
  stage_code          TEXT NOT NULL,
  stage_ordinal       INTEGER NOT NULL CHECK (stage_ordinal >= 0),
  status              TEXT NOT NULL CHECK (
    status IN ('SUCCEEDED', 'BLOCKED', 'FAILED', 'INVALID', 'NOT_APPLICABLE')
  ),
  produced_row_count  INTEGER NOT NULL CHECK (produced_row_count >= 0),
  error_code          TEXT,
  UNIQUE (run_id, stage_code),
  UNIQUE (run_id, stage_ordinal)
);

-- 12. Common result identity root. Stable keys, not row ids, enter the canonical result hash.
CREATE TABLE run_result (
  id                 TEXT PRIMARY KEY,
  run_id             TEXT NOT NULL REFERENCES scenario_run(id) ON DELETE RESTRICT,
  stable_key         TEXT NOT NULL,
  result_kind        TEXT NOT NULL CHECK (
    result_kind IN ('GEOMETRIC_ACCESS', 'MODELED_CONTACT', 'CANDIDATE_SESSION',
                    'SCHEDULED_SESSION', 'TRANSFER_ALLOCATION', 'RUN_EVENT', 'METRIC', 'ANNOTATION')
  ),
  calculation_status TEXT NOT NULL CHECK (
    calculation_status IN ('COMPUTED', 'BLOCKED', 'INVALID', 'KNOWN_ZERO', 'NOT_APPLICABLE')
  ),
  decision_grade     TEXT CHECK (
    decision_grade IS NULL
    OR decision_grade IN ('VERIFIED', 'ENGINEERING_ESTIMATE', 'CONCEPT_ONLY', 'BLOCKED')
  ),
  UNIQUE (run_id, stable_key),
  CONSTRAINT run_result_status_grade_ck CHECK (
    (calculation_status IN ('COMPUTED', 'KNOWN_ZERO')
      AND decision_grade IN ('VERIFIED', 'ENGINEERING_ESTIMATE', 'CONCEPT_ONLY'))
    OR (calculation_status = 'BLOCKED' AND decision_grade = 'BLOCKED')
    OR (calculation_status IN ('INVALID', 'NOT_APPLICABLE') AND decision_grade IS NULL)
  )
);

-- 13. Pure geometric access. Maximum elevation is forbidden for a synthetic injected contact and
-- mandatory for an orbit-derived one, exactly as ADR-0002 requires of the PostgreSQL schema.
CREATE TABLE geometric_access (
  result_id               TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  scenario_station_id     TEXT NOT NULL REFERENCES scenario_station(id) ON DELETE RESTRICT,
  true_aos_us             INTEGER NOT NULL,
  true_los_us             INTEGER NOT NULL,
  clipped_start_us        INTEGER NOT NULL,
  clipped_end_us          INTEGER NOT NULL,
  maximum_elevation_udeg  INTEGER,
  maximum_elevation_at_us INTEGER,
  contact_source          TEXT NOT NULL CHECK (contact_source IN ('ORBIT_DERIVED', 'SYNTHETIC_INJECTED')),
  CONSTRAINT geometric_true_interval_ck CHECK (true_aos_us < true_los_us),
  CONSTRAINT geometric_clipped_interval_ck CHECK (
    clipped_start_us < clipped_end_us
    AND true_aos_us <= clipped_start_us
    AND clipped_end_us <= true_los_us
  ),
  CONSTRAINT geometric_elevation_source_ck CHECK (
    (contact_source = 'ORBIT_DERIVED'
      AND maximum_elevation_udeg IS NOT NULL
      AND maximum_elevation_udeg BETWEEN 0 AND 90000000
      AND maximum_elevation_at_us IS NOT NULL
      AND true_aos_us <= maximum_elevation_at_us
      AND maximum_elevation_at_us < true_los_us)
    OR
    (contact_source = 'SYNTHETIC_INJECTED'
      AND maximum_elevation_udeg IS NULL
      AND maximum_elevation_at_us IS NULL)
  )
);

-- 14. Guard and eligibility applied.
CREATE TABLE modeled_contact (
  result_id           TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  geometric_result_id TEXT NOT NULL UNIQUE REFERENCES geometric_access(result_id) ON DELETE RESTRICT,
  link_compatibility  TEXT NOT NULL CHECK (link_compatibility IN ('ELIGIBLE', 'INELIGIBLE', 'UNKNOWN')),
  usable_start_us     INTEGER,
  usable_end_us       INTEGER,
  primary_reason_code TEXT,
  CONSTRAINT modeled_interval_ck CHECK (
    (usable_start_us IS NULL AND usable_end_us IS NULL)
    OR (usable_start_us IS NOT NULL AND usable_end_us IS NOT NULL AND usable_start_us < usable_end_us)
  )
);

-- 15. Conflict-before capacity. The only authoritative per-contact logical capacity value.
CREATE TABLE candidate_session (
  result_id                 TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  modeled_contact_result_id TEXT NOT NULL UNIQUE REFERENCES modeled_contact(result_id) ON DELETE RESTRICT,
  capacity_bytes            TEXT CHECK (capacity_bytes IS NULL OR NOT capacity_bytes GLOB '*[^0-9]*'),
  conflict_component_key    TEXT
);

-- 16. A selected whole opportunity. Capacity is derived through the candidate, never copied.
CREATE TABLE scheduled_session (
  result_id           TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  candidate_result_id TEXT NOT NULL UNIQUE REFERENCES candidate_session(result_id) ON DELETE RESTRICT,
  selection_ordinal   INTEGER NOT NULL CHECK (selection_ordinal >= 0),
  primary_reason_code TEXT NOT NULL
);

-- 17. Planned logical-byte placement. P0 has no received, verified or acknowledged byte.
CREATE TABLE transfer_allocation (
  result_id                    TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  scheduled_session_result_id  TEXT NOT NULL REFERENCES scheduled_session(result_id) ON DELETE RESTRICT,
  scenario_payload_id          TEXT NOT NULL REFERENCES scenario_payload(id) ON DELETE RESTRICT,
  allocation_ordinal           INTEGER NOT NULL CHECK (allocation_ordinal >= 0),
  logical_offset_start         TEXT NOT NULL CHECK (NOT logical_offset_start GLOB '*[^0-9]*'),
  logical_bytes                TEXT NOT NULL CHECK (NOT logical_bytes GLOB '*[^0-9]*'),
  started_at_us                INTEGER NOT NULL,
  ended_at_us                  INTEGER NOT NULL,
  modeled_progress_after_bytes TEXT NOT NULL CHECK (NOT modeled_progress_after_bytes GLOB '*[^0-9]*'),
  modeled_tx_complete_at_us    INTEGER,
  deadline_status              TEXT,
  remaining_after_bytes        TEXT NOT NULL CHECK (NOT remaining_after_bytes GLOB '*[^0-9]*'),
  primary_reason_code          TEXT NOT NULL,
  UNIQUE (scheduled_session_result_id, allocation_ordinal),
  CONSTRAINT allocation_interval_ck CHECK (started_at_us < ended_at_us),
  CONSTRAINT allocation_complete_time_ck CHECK (
    modeled_tx_complete_at_us IS NULL
    OR (started_at_us < modeled_tx_complete_at_us AND modeled_tx_complete_at_us <= ended_at_us)
  )
);

-- 18. Shared queue/storage event envelope. (run_id, event_at, event_order) is a total order.
CREATE TABLE run_event (
  result_id               TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  run_id                  TEXT NOT NULL REFERENCES scenario_run(id) ON DELETE RESTRICT,
  event_at_us             INTEGER NOT NULL,
  event_order             INTEGER NOT NULL CHECK (event_order >= 0),
  event_domain            TEXT NOT NULL CHECK (event_domain IN ('QUEUE', 'STORAGE')),
  event_kind              TEXT NOT NULL,
  scenario_payload_id     TEXT REFERENCES scenario_payload(id) ON DELETE RESTRICT,
  allocation_result_id    TEXT REFERENCES transfer_allocation(result_id) ON DELETE RESTRICT,
  delta_logical_bytes     TEXT,
  remaining_logical_bytes TEXT,
  delta_storage_bytes     TEXT,
  occupancy_bytes         TEXT,
  reserve_breach_bytes    TEXT,
  rejected_bytes          TEXT,
  reason_code             TEXT NOT NULL,
  UNIQUE (run_id, event_at_us, event_order),
  CONSTRAINT event_domain_fields_ck CHECK (
    (event_domain = 'QUEUE'
      AND delta_storage_bytes IS NULL AND occupancy_bytes IS NULL
      AND reserve_breach_bytes IS NULL AND rejected_bytes IS NULL)
    OR
    (event_domain = 'STORAGE'
      AND delta_logical_bytes IS NULL AND remaining_logical_bytes IS NULL)
  ),
  CONSTRAINT event_exact_bytes_ck CHECK (
    (delta_logical_bytes IS NULL OR NOT delta_logical_bytes GLOB '*[^-0-9]*')
    AND (remaining_logical_bytes IS NULL OR NOT remaining_logical_bytes GLOB '*[^0-9]*')
    AND (delta_storage_bytes IS NULL OR NOT delta_storage_bytes GLOB '*[^-0-9]*')
    AND (occupancy_bytes IS NULL OR NOT occupancy_bytes GLOB '*[^0-9]*')
    AND (reserve_breach_bytes IS NULL OR NOT reserve_breach_bytes GLOB '*[^0-9]*')
    AND (rejected_bytes IS NULL OR NOT rejected_bytes GLOB '*[^0-9]*')
  )
);

-- 19. Versioned materialized KPI. Values are exact integers held as canonical decimal text.
CREATE TABLE run_metric (
  result_id           TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  metric_code         TEXT NOT NULL,
  scope_code          TEXT NOT NULL,
  scenario_station_id TEXT REFERENCES scenario_station(id) ON DELETE RESTRICT,
  scenario_payload_id TEXT REFERENCES scenario_payload(id) ON DELETE RESTRICT,
  unit_code           TEXT NOT NULL,
  definition_revision TEXT NOT NULL,
  accounting_layer    TEXT,
  value_integer       TEXT CHECK (value_integer IS NULL OR NOT value_integer GLOB '*[^-0-9]*'),
  CONSTRAINT metric_one_dimension_ck CHECK (
    (scenario_station_id IS NULL) OR (scenario_payload_id IS NULL)
  )
);

-- 20. Warning and decision-reason rows share one envelope; repeated codes are repeated rows.
CREATE TABLE run_annotation (
  result_id              TEXT PRIMARY KEY REFERENCES run_result(id) ON DELETE RESTRICT,
  subject_result_id      TEXT REFERENCES run_result(id) ON DELETE RESTRICT,
  annotation_kind        TEXT NOT NULL CHECK (annotation_kind IN ('WARNING', 'DECISION_REASON', 'VALIDATION')),
  code                   TEXT NOT NULL,
  severity               TEXT NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'ERROR')),
  ordinal                INTEGER NOT NULL CHECK (ordinal >= 0),
  rule_revision          TEXT NOT NULL,
  compared_result_id     TEXT REFERENCES run_result(id) ON DELETE RESTRICT,
  criterion_code         TEXT,
  criterion_value_integer TEXT CHECK (criterion_value_integer IS NULL OR NOT criterion_value_integer GLOB '*[^-0-9]*'),
  criterion_value_text   TEXT,
  unit_code              TEXT,
  message                TEXT,
  CONSTRAINT annotation_criterion_ck CHECK (
    criterion_value_integer IS NULL OR criterion_value_text IS NULL
  )
);

-- 21. Immutable rendered result document.
-- The typed rows above remain the relational record of the run; this is the versioned execution
-- artifact, exactly the role ADR-008 gives `input_snapshot.canonical_payload` on the input side.
-- It exists so a restarted process can serve GET /runs/{id}/results without recomputing, and its
-- hash is checked against scenario_run.result_content_hash on read.
CREATE TABLE run_result_document (
  run_id                    TEXT PRIMARY KEY REFERENCES scenario_run(id) ON DELETE RESTRICT,
  canonicalization_revision TEXT NOT NULL,
  content_sha256            TEXT NOT NULL CHECK (length(content_sha256) = 64),
  document                  TEXT NOT NULL
);

-- Lookup indexes.
CREATE INDEX scenario_revision_history_idx ON scenario_revision(scenario_id, revision_no DESC);
CREATE INDEX scenario_station_load_idx ON scenario_station(scenario_revision_id, stable_key);
CREATE INDEX scenario_payload_ready_idx ON scenario_payload(scenario_revision_id, ready_at_us, queue_sequence);
CREATE INDEX run_snapshot_idx ON scenario_run(input_snapshot_id, requested_at_us DESC);
CREATE INDEX run_stage_run_idx ON run_stage(run_id, stage_ordinal);
CREATE INDEX result_run_kind_idx ON run_result(run_id, result_kind, stable_key);
CREATE INDEX event_run_timeline_idx ON run_event(run_id, event_at_us, event_order);
CREATE INDEX metric_compare_idx ON run_metric(metric_code, definition_revision, unit_code, scope_code);

-- Immutability. The application service is the primary guard; these triggers are the second
-- line of defence so a stray statement cannot rewrite a terminal run or a stored result.
CREATE TRIGGER scenario_run_immutable BEFORE UPDATE ON scenario_run
BEGIN
  SELECT RAISE(ABORT, 'terminal run rows are immutable');
END;

CREATE TRIGGER scenario_run_no_delete BEFORE DELETE ON scenario_run
BEGIN
  SELECT RAISE(ABORT, 'terminal run rows are retained, not deleted');
END;

CREATE TRIGGER run_stage_immutable BEFORE UPDATE ON run_stage
BEGIN
  SELECT RAISE(ABORT, 'run stage rows are immutable');
END;

CREATE TRIGGER run_result_immutable BEFORE UPDATE ON run_result
BEGIN
  SELECT RAISE(ABORT, 'run result rows are immutable');
END;

CREATE TRIGGER run_result_no_delete BEFORE DELETE ON run_result
BEGIN
  SELECT RAISE(ABORT, 'run result rows are retained, not deleted');
END;

CREATE TRIGGER input_snapshot_immutable BEFORE UPDATE ON input_snapshot
BEGIN
  SELECT RAISE(ABORT, 'input snapshots are immutable');
END;

CREATE TRIGGER run_result_document_immutable BEFORE UPDATE ON run_result_document
BEGIN
  SELECT RAISE(ABORT, 'stored result documents are immutable');
END;

CREATE TRIGGER scenario_revision_published_immutable BEFORE UPDATE ON scenario_revision
WHEN OLD.lifecycle_status = 'PUBLISHED'
BEGIN
  SELECT RAISE(ABORT, 'published scenario revisions are immutable');
END;
