"""The ORBIT_DERIVED vertical slice: one orbit assumption becomes contacts, capacity and a plan.

These cases exercise the *product* path (not the cross-tool oracle in `test_orbit_cross_tool.py`).
They prove that the same verified orbit engine reached through the `ContactProvider` port produces
identical results over the API and the CLI, that the generated windows flow into the existing
capacity and model-output prioritisation, and that the ADR-0002 provenance split is enforced.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

from fastapi.testclient import TestClient

from semantix_passbudget.adapters.memory_repository import InMemoryRunRepository
from semantix_passbudget.adapters.orbit.provider import OrbitContactProvider
from semantix_passbudget.adapters.synthetic_contact import SyntheticContactProvider
from semantix_passbudget.application.service import RunScenarioService
from semantix_passbudget.interfaces.api.app import app
from semantix_passbudget.interfaces.cli.main import main
from semantix_passbudget.interfaces.dto import load_fixture_source, packaged_fixture_path

FIXTURE = "PB-GOLDEN-ORB-01"


def _service() -> RunScenarioService:
    return RunScenarioService(
        SyntheticContactProvider(),
        InMemoryRunRepository(),
        orbit_provider=OrbitContactProvider(),
    )


def _fixture_content() -> dict:
    return json.loads(packaged_fixture_path(FIXTURE).read_text(encoding="utf-8"))


def test_orbit_derived_generates_contacts_capacity_and_a_plan() -> None:
    result = _service().run(load_fixture_source(FIXTURE).to_domain()).result
    metrics = result["metrics"]

    # Contacts are generated by the provider, not injected: seven daily passes across two stations.
    assert result["contact_source"] == "ORBIT_DERIVED"
    assert metrics["geometric_contact_count"] == 7
    assert {s["station_key"]: s["geometric_contact_count"] for s in metrics["stations"]} == {
        "SYN-GS-MIDLAT": 4,
        "SYN-GS-EQUATOR": 3,
    }
    # Each generated access carries orbit geometry the synthetic path never has.
    for access in result["geometric_accesses"]:
        assert access["maximum_elevation_udeg"] is not None
        assert access["true_aos"] <= access["maximum_elevation_at"] < access["true_los"]

    # The windows feed the assumed-throughput capacity and the model-output prioritisation.
    assert metrics["candidate_capacity_sum_bytes"] > 0
    progress = {item["payload_key"]: item["state"] for item in result["payload_progress"]}
    assert progress == {
        "WILDFIRE-DETECT": "COMPLETED",
        "FIGHTER-TRACK": "COMPLETED",
        "SHIP-DETECT": "PARTIAL",
    }
    assert metrics["payload_remaining_bytes"] > 0  # ship backlog is deferred, not silently dropped

    # Provenance and manifest name the real engine revisions, and the safety label is explicit.
    assert result["provenance"]["contact_provider"] == "ORB-PASS-01"
    assert result["provenance"]["synthetic"] is False
    assert result["engine_manifest"]["orbit_provider_revision"] == "ORB-PASS-01"
    assert result["engine_manifest"]["frame_transform_revision"] != "NOT_APPLICABLE"
    assert result["orbit_dependency"]["calculation_status"] == "COMPUTED"
    assert "가정 기반 추정값" in result["safety_notice"]


def test_orbit_derived_is_deterministic_without_network() -> None:
    first = _service().run(load_fixture_source(FIXTURE).to_domain())
    second = _service().run(load_fixture_source(FIXTURE).to_domain())
    assert first.input_snapshot_hash == second.input_snapshot_hash
    assert first.result_content_hash == second.result_content_hash


def test_api_and_cli_share_one_orbit_domain_path(tmp_path: Path) -> None:
    """The HTTP and CLI entry points must reach the same domain result, not two implementations."""
    client = TestClient(app, raise_server_exceptions=False)
    created = client.post("/api/v1/runs", json={"fixture": FIXTURE})
    assert created.status_code == 201, created.text
    results = client.get(f"/api/v1/runs/{created.json()['run_id']}/results")
    assert results.status_code == 200

    output = tmp_path / "orbit.json"
    assert main(["run", FIXTURE, "--output", str(output)]) == 0
    cli_result = json.loads(output.read_text(encoding="utf-8"))

    assert created.json()["result_content_hash"] == cli_result["result_content_hash"]
    assert created.json()["input_snapshot_hash"] == cli_result["input_snapshot_hash"]
    assert results.json()["result"] == cli_result["result"]


def test_synthetic_injected_still_forbids_orbit_inputs() -> None:
    client = TestClient(app, raise_server_exceptions=False)
    content = json.loads(packaged_fixture_path("PB-GOLDEN-CORE-01").read_text(encoding="utf-8"))
    content["stations"][0]["site"] = {
        "latitude_udeg": 37_600_000,
        "longitude_east_udeg": 127_000_000,
        "ellipsoidal_height_mm": 100_000,
        "minimum_elevation_udeg": 5_000_000,
    }
    response = client.post("/api/v1/runs", json={"snapshot": content})
    assert response.status_code == 422
    assert response.json()["error"]["code"] == "SYNTHETIC_FORBIDS_STATION_SITE"


def test_orbit_derived_requires_station_geometry() -> None:
    client = TestClient(app, raise_server_exceptions=False)
    content = _fixture_content()
    del content["stations"][0]["site"]
    response = client.post("/api/v1/runs", json={"snapshot": content})
    assert response.status_code == 422
    assert response.json()["error"]["code"] == "MISSING_STATION_SITE"


def test_orbit_derived_rejects_injected_contacts() -> None:
    client = TestClient(app, raise_server_exceptions=False)
    content = _fixture_content()
    content["contacts"] = [
        {
            "stable_key": "X1",
            "station_key": "SYN-GS-MIDLAT",
            "true_interval": {"start": "2026-09-03T01:00:00Z", "end": "2026-09-03T01:10:00Z"},
        }
    ]
    response = client.post("/api/v1/runs", json={"snapshot": content})
    assert response.status_code == 422
    assert response.json()["error"]["code"] == "ORBIT_DERIVED_CONTACTS_ARE_GENERATED"


def test_orbit_derived_requires_an_orbit_assumption() -> None:
    client = TestClient(app, raise_server_exceptions=False)
    content = _fixture_content()
    del content["orbit"]
    response = client.post("/api/v1/runs", json={"snapshot": content})
    assert response.status_code == 422
    assert response.json()["error"]["code"] == "MISSING_ORBIT_SPEC"


def test_a_service_without_an_orbit_provider_refuses_orbit_derived() -> None:
    """No fallback to the synthetic provider (ADR-0004): a misconfigured deployment fails loudly."""
    service = RunScenarioService(SyntheticContactProvider(), InMemoryRunRepository())
    snapshot = load_fixture_source(FIXTURE).to_domain()
    try:
        service.run(snapshot)
    except Exception as exc:
        assert "ORBIT_PROVIDER_NOT_CONFIGURED" in str(type(exc)) or "orbit provider" in str(exc)
    else:  # pragma: no cover - the run must not succeed without an orbit provider
        raise AssertionError("a service with no orbit provider must refuse ORBIT_DERIVED")


def test_a_user_supplied_tle_also_generates_contacts() -> None:
    """The tool lets a user try their own orbit; a TLE is request data, not a KMU claim."""
    content = _fixture_content()
    # A synthetic, self-consistent circular LEO TLE (not a real object).
    content["fixture_id"] = "PB-PROBE-TLE"
    content["orbit"] = {
        "kind": "GP_TLE",
        "tle": {
            "line_1": "1 99999U 26001A   26246.00000000  .00000000  00000+0  00000+0 0  9995",
            "line_2": "2 99999  98.0000  90.0000 0000010   0.0000   0.0000 14.90000000000010",
        },
    }
    run = _service().run(
        _content_to_snapshot(content),
    )
    assert run.result["contact_source"] == "ORBIT_DERIVED"
    assert run.result["engine_manifest"]["frame_transform_revision"] == "TEME_GMST82_TO_ITRF_V1"


def _content_to_snapshot(content: dict):  # type: ignore[no-untyped-def]
    from semantix_passbudget.interfaces.dto import parse_fixture_content

    return parse_fixture_content(copy.deepcopy(content)).to_domain()
