"""Cross-tool orbit verification: the product engine against the NASA GMAT expected tables.

This is the executable form of `EVD-ORB-01` and `EVD-ORB-02`. The expected values are read from
committed artifacts that were produced by an independent tool; nothing here was generated by the
code under test, and no tolerance in this file may be widened to make a test pass. The ceilings
mirror `docs/specs/ORBIT_VERIFICATION_CONTRACT.md` §10.1 and are duplicated deliberately: if
somebody edits one, this test fails and points at the other.
"""

from __future__ import annotations

import json
import pathlib
from datetime import UTC, datetime

import pytest

from semantix_passbudget.adapters.orbit.passes import (
    StationSite,
    find_passes,
    sgp4_position_source,
    two_body_position_source,
)
from semantix_passbudget.adapters.orbit.twobody import circular_state_from_elements

EVIDENCE = pathlib.Path(__file__).resolve().parents[2] / "evidence" / "orbit"

# Contract §10.1. The gate, not a knob.
CEILING_AOS_S = 1.000
CEILING_LOS_S = 1.000
CEILING_DURATION_S = 2.000
CEILING_MAX_ELEVATION_DEG = 0.050
CEILING_MAX_ELEVATION_TIME_S = 2.000

UNIX_EPOCH = datetime(1970, 1, 1, tzinfo=UTC)


def _parse(text: str) -> datetime:
    return datetime.strptime(text, "%Y-%m-%dT%H:%M:%S.%f%z").astimezone(UTC)


def _load(fixture_id: str) -> tuple[dict, dict]:
    inputs_path = EVIDENCE / fixture_id / "inputs.json"
    if fixture_id == "EVD-ORB-01" and not inputs_path.is_file():
        # EVD-ORB-01 is derived from a CelesTrak-redistributed TLE and is withheld from the public
        # repository until Q-ORB-LICENSE-01 is resolved (see .gitignore and the verification
        # contract §11). Where the local evidence is present the case runs and must pass; where it
        # is deliberately absent it is skipped, never counted as a pass. The fully synthetic
        # EVD-ORB-02 remains the committed public cross-tool gate and always runs.
        pytest.skip(
            f"{fixture_id} evidence is withheld pending Q-ORB-LICENSE-01; "
            "EVD-ORB-02 covers the public cross-tool gate"
        )
    expected_path = EVIDENCE / fixture_id / "expected_table.json"
    for required_path in (inputs_path, expected_path):
        if not required_path.is_file():
            pytest.fail(f"Required orbit evidence is missing: {required_path}")
    inputs = json.loads(inputs_path.read_text(encoding="utf-8"))
    expected = json.loads(expected_path.read_text(encoding="utf-8"))
    return inputs, expected


def test_only_withheld_tle_inputs_may_skip(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setitem(globals(), "EVIDENCE", tmp_path)
    with pytest.raises(pytest.skip.Exception, match="EVD-ORB-01 evidence is withheld"):
        _load("EVD-ORB-01")


@pytest.mark.parametrize("fixture_id", ["EVD-ORB-02", "UNKNOWN-FIXTURE"])
def test_required_or_unknown_fixture_inputs_missing_fail(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch, fixture_id: str
) -> None:
    monkeypatch.setitem(globals(), "EVIDENCE", tmp_path)
    with pytest.raises(pytest.fail.Exception, match=r"Required orbit evidence is missing:.*inputs"):
        _load(fixture_id)


@pytest.mark.parametrize("fixture_id", ["EVD-ORB-01", "EVD-ORB-02"])
def test_expected_table_missing_never_skips(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch, fixture_id: str
) -> None:
    monkeypatch.setitem(globals(), "EVIDENCE", tmp_path)
    fixture_dir = tmp_path / fixture_id
    fixture_dir.mkdir()
    (fixture_dir / "inputs.json").write_text("{}", encoding="utf-8")
    with pytest.raises(
        pytest.fail.Exception, match=r"Required orbit evidence is missing:.*expected"
    ):
        _load(fixture_id)


def _sites(inputs: dict) -> tuple[StationSite, ...]:
    return tuple(
        StationSite(
            station_key=s["station_key"],
            latitude_deg=float(s["latitude_deg"]),
            longitude_east_deg=float(s["longitude_deg_east"]),
            ellipsoidal_height_m=float(s["ellipsoidal_height_m"]),
            minimum_elevation_deg=float(s["minimum_elevation_deg"]),
        )
        for s in inputs["stations"]
    )


def _position_source(inputs: dict):
    if inputs["kind"] == "GP_TLE":
        return sgp4_position_source(inputs["tle"]["line_1"], inputs["tle"]["line_2"])
    state = inputs["state"]
    mu = float(inputs["central_body"]["mu_m3_per_s2"])
    position, velocity = circular_state_from_elements(
        semi_major_axis_m=float(state["semi_major_axis_m"]),
        inclination_deg=float(state["inclination_deg"]),
        raan_deg=float(state["raan_deg"]),
        argument_of_perigee_deg=float(state["argument_of_perigee_deg"]),
        true_anomaly_deg=float(state["true_anomaly_deg"]),
        eccentricity=float(state["eccentricity"]),
        mu=mu,
    )
    epoch_s = (_parse(inputs["epoch_utc"]) - UNIX_EPOCH).total_seconds()
    return two_body_position_source(epoch_s, position, velocity, mu)


def _run(fixture_id: str, window_name: str):
    inputs, expected = _load(fixture_id)
    bounds = next(w for w in inputs["analysis_windows"] if w["window"] == window_name)
    window = next(w for w in expected["windows"] if w["window"] == window_name)
    produced = find_passes(
        _position_source(inputs),
        _sites(inputs),
        _parse(bounds["start_utc"]),
        _parse(bounds["end_utc"]),
        fixture_id,
    )
    return inputs, window, produced


CASES = [
    ("EVD-ORB-01", "W1"),
    ("EVD-ORB-01", "W2"),
    ("EVD-ORB-02", "W1"),
    ("EVD-ORB-02", "W2"),
]


@pytest.mark.parametrize(("fixture_id", "window_name"), CASES)
def test_pass_count_matches_the_independent_oracle(fixture_id: str, window_name: str) -> None:
    inputs, window, produced = _run(fixture_id, window_name)
    for station in (s["station_key"] for s in inputs["stations"]):
        expected_count = sum(1 for p in window["passes"] if p["station_key"] == station)
        actual_count = sum(1 for p in produced if p.station_key == station)
        assert actual_count == expected_count, (
            f"{fixture_id} {window_name} {station}: "
            f"oracle says {expected_count} passes, engine says {actual_count}"
        )


@pytest.mark.parametrize(("fixture_id", "window_name"), CASES)
def test_a_station_with_no_contact_is_agreed_not_merely_absent(
    fixture_id: str, window_name: str
) -> None:
    """Contract §8.6: 'saw nothing' is a result, and both tools must produce it."""
    _inputs, window, produced = _run(fixture_id, window_name)
    silent_in_product = {s for s in window["stations_reported"]} - {p.station_key for p in produced}
    assert sorted(silent_in_product) == sorted(window["zero_contact_stations"])


@pytest.mark.parametrize(("fixture_id", "window_name"), CASES)
def test_every_pass_is_inside_every_ceiling(fixture_id: str, window_name: str) -> None:
    _inputs, window, produced = _run(fixture_id, window_name)
    by_station: dict[str, list] = {}
    for event in produced:
        by_station.setdefault(event.station_key, []).append(event)
    expected_by_station: dict[str, list] = {}
    for row in window["passes"]:
        expected_by_station.setdefault(row["station_key"], []).append(row)

    compared = 0
    for station, rows in expected_by_station.items():
        # Matched by ordinal, never by nearest time (contract §9).
        for want, got in zip(rows, by_station[station], strict=True):
            compared += 1
            # A clipped boundary is not a computed crossing; comparing it is a tautology.
            if not got.clipped_start:
                assert abs((got.aos - _parse(want["aos_utc"])).total_seconds()) <= CEILING_AOS_S
            if not got.clipped_end:
                assert abs((got.los - _parse(want["los_utc"])).total_seconds()) <= CEILING_LOS_S
            assert abs(got.duration_s - float(want["duration_s"])) <= CEILING_DURATION_S
            assert (
                abs(got.maximum_elevation_deg - float(want["maximum_elevation_deg"]))
                <= CEILING_MAX_ELEVATION_DEG
            )
            assert (
                abs(
                    (
                        got.maximum_elevation_time - _parse(want["maximum_elevation_time_utc"])
                    ).total_seconds()
                )
                <= CEILING_MAX_ELEVATION_TIME_S
            )
    assert compared == len(window["passes"])


@pytest.mark.parametrize(("fixture_id", "window_name"), CASES)
def test_repeated_runs_are_byte_identical(fixture_id: str, window_name: str) -> None:
    """Contract §9: determinism is not a tolerance."""
    _i, _w, first = _run(fixture_id, window_name)
    _i2, _w2, second = _run(fixture_id, window_name)
    assert first == second


@pytest.mark.parametrize(("fixture_id", "window_name"), CASES)
def test_results_are_ordered_and_clipped_to_the_window(fixture_id: str, window_name: str) -> None:
    inputs, _window, produced = _run(fixture_id, window_name)
    bounds = next(w for w in inputs["analysis_windows"] if w["window"] == window_name)
    start, end = _parse(bounds["start_utc"]), _parse(bounds["end_utc"])
    keys = [(e.aos, e.los, e.station_key, e.stable_key) for e in produced]
    assert keys == sorted(keys), "contacts must be ordered by (aos, los, station, stable key)"
    for event in produced:
        assert start <= event.aos < end
        assert start < event.los <= end
        assert event.aos < event.los
        assert event.clipped_start == (event.aos == start)
        assert event.clipped_end == (event.los == end)


def test_the_tangent_pass_is_present_and_not_filtered_out() -> None:
    """Contract §8.7: a pass that barely clears the mask is reported, not discarded.

    This is the worst-conditioned geometry in either fixture -- dE/dt approaches zero at the
    crossing -- so it is the case most likely to be silently dropped by a sloppier solver.
    """
    _inputs, _window, produced = _run("EVD-ORB-02", "W1")
    tangent = [
        e for e in produced if e.station_key == "SYN-GS-TANGENT" and e.maximum_elevation_deg < 5.5
    ]
    assert tangent, "the tangent pass disappeared from the result"
    assert min(e.maximum_elevation_deg for e in tangent) > 5.0


def test_the_polar_station_sees_nothing_in_the_tle_fixture() -> None:
    """Analytic guarantee from contract §6.1, independent of any tool.

    A 51.6312 deg inclination orbit puts the ground track 33.37 deg away from an 85 deg N
    station, against a 15.82 deg visibility half-angle. No propagator may find a pass here.
    """
    _inputs, _window, produced = _run("EVD-ORB-01", "W1")
    assert not [e for e in produced if e.station_key == "SYN-GS-POLAR"]
