"""SQLite run and result persistence: the default local store.

Implements the same `RunRepository` contract as the in-memory and PostgreSQL adapters, writing
the same typed relational rows. It stores and reads what the application service produced; it
never calculates anything, and it never derives a hash of its own.

Representation rules, mirrored from `db/sqlite/schema_v1.sql`:

* exact integers cross the boundary as canonical decimal text, because SQLite `INTEGER` is signed
  64-bit while the byte domain is `numeric(20,0)`/`numeric(39,0)`;
* timestamps cross as UTC epoch microseconds and come back as the same canonical `Z` string;
* every statement uses parameter binding;
* every identifier is generated by the application.
"""

from __future__ import annotations

import json
import sqlite3
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

from semantix_passbudget.adapters.sqlite.schema import connect, migrate
from semantix_passbudget.application.decompose import decompose_snapshot
from semantix_passbudget.domain.canonical import CANONICALIZATION_REVISION, canonical_bytes
from semantix_passbudget.domain.enums import ContactSource, StorageMode
from semantix_passbudget.domain.models import ScenarioSnapshot
from semantix_passbudget.ports.persisted_rows import PersistedRows, result_rows
from semantix_passbudget.ports.run_repository import StoredRun

JSON_SCHEMA_ID = "semantix.passbudget.input-snapshot.v0.2"
EPOCH = datetime(1970, 1, 1, tzinfo=UTC)


class SqlitePersistenceError(RuntimeError):
    """Redacted local-persistence failure.

    The driver exception is not chained, so a filesystem path never reaches an API response.
    """


@contextmanager
def _redacted(operation: str) -> Iterator[None]:
    try:
        yield
    except sqlite3.Error:
        raise SqlitePersistenceError(f"local persistence operation failed: {operation}") from None


def _us(value: str | None) -> int | None:
    """Canonical `...Z` timestamp -> UTC epoch microseconds."""
    if value is None:
        return None
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    delta = parsed - EPOCH
    return (delta.days * 86_400 + delta.seconds) * 1_000_000 + delta.microseconds


def _iso(value: int | None) -> str | None:
    """UTC epoch microseconds -> the canonical fixed six-digit `...Z` timestamp."""
    if value is None:
        return None
    seconds, microseconds = divmod(value, 1_000_000)
    moment = datetime.fromtimestamp(seconds, tz=UTC).replace(microsecond=microseconds)
    return moment.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _exact(value: int | None) -> str | None:
    """Exact integer -> canonical decimal text. No float ever appears on this path."""
    if value is None:
        return None
    if not isinstance(value, int) or isinstance(value, bool):
        raise SqlitePersistenceError("exact integer columns accept int only")
    return str(value)


def _int(value: Any) -> int | None:
    """Exact decimal text or INTEGER column -> Python int. Never a float."""
    return None if value is None else int(value)


class SqliteRunRepository:
    """Run persistence in one local SQLite file.

    A short-lived connection is opened per operation. SQLite connections are not safe to share
    between threads, and the API serves requests from a worker pool, so per-operation connections
    are both simpler and correct. WAL mode keeps a reader from blocking behind a writer.
    """

    def __init__(self, path: Path | str) -> None:
        self._path = str(path)
        with self._connection() as connection:
            migrate(connection)

    @property
    def path(self) -> str:
        return self._path

    @contextmanager
    def _connection(self) -> Iterator[sqlite3.Connection]:
        connection = connect(self._path)
        try:
            yield connection
        finally:
            connection.close()

    # ------------------------------------------------------------------ writing

    def add(self, run: StoredRun) -> None:
        if run.snapshot is None:
            raise SqlitePersistenceError(
                "a persisted run requires the resolved input snapshot it was computed from"
            )
        with _redacted("store run"), self._connection() as connection:
            if self._run_exists(connection, run.run_id):
                raise SqlitePersistenceError(
                    "run identifiers are immutable and may not be overwritten"
                )
            connection.execute("BEGIN IMMEDIATE")
            try:
                revision_id, station_ids, payload_ids = self._ensure_scenario(
                    connection, run.snapshot
                )
                snapshot_id = self._ensure_snapshot(connection, run, revision_id)
                manifest_id = self._ensure_manifest(connection, run.result["engine_manifest"])
                self._write_run(connection, run, snapshot_id, manifest_id, station_ids, payload_ids)
                connection.execute("COMMIT")
            except Exception:
                connection.execute("ROLLBACK")
                raise

    @staticmethod
    def _run_exists(connection: sqlite3.Connection, run_id: str) -> bool:
        return (
            connection.execute("SELECT 1 FROM scenario_run WHERE id = ?", (run_id,)).fetchone()
            is not None
        )

    def _ensure_scenario(
        self, connection: sqlite3.Connection, snapshot: ScenarioSnapshot
    ) -> tuple[str, dict[str, str], dict[str, str]]:
        graph = decompose_snapshot(snapshot)
        scenario_key = snapshot.fixture_id
        row = connection.execute(
            "SELECT id FROM scenario WHERE stable_key = ?", (scenario_key,)
        ).fetchone()
        if row is None:
            scenario_id = str(uuid4())
            connection.execute(
                "INSERT INTO scenario (id, stable_key, name, description, is_preset, "
                "created_at_us) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    scenario_id,
                    scenario_key,
                    scenario_key[:160],
                    snapshot.decision_question[:1000],
                    1,
                    self._now_us(),
                ),
            )
        else:
            scenario_id = str(row["id"])

        revision_hash = self._revision_hash(snapshot, graph)
        existing = connection.execute(
            "SELECT id FROM scenario_revision WHERE scenario_id = ? AND semantic_hash = ?",
            (scenario_id, revision_hash),
        ).fetchone()
        if existing is not None:
            revision_id = str(existing["id"])
            return (
                revision_id,
                self._keys(connection, "scenario_station", revision_id),
                self._keys(connection, "scenario_payload", revision_id),
            )

        revision_no = (
            int(
                connection.execute(
                    "SELECT count(*) AS n FROM scenario_revision WHERE scenario_id = ?",
                    (scenario_id,),
                ).fetchone()["n"]
            )
            + 1
        )
        revision_id = str(uuid4())
        storage = snapshot.storage
        enabled = storage.mode is StorageMode.ENABLED
        manifest = self._manifest()
        connection.execute(
            "INSERT INTO scenario_revision ("
            " id, scenario_id, revision_no, lifecycle_status, schema_version, decision_question,"
            " analysis_start_us, analysis_end_us, analysis_mode, contact_source,"
            " synthetic_contact_provider_revision, orbit_revision_id, policy_revision_key,"
            " spacecraft_key, storage_mode, physical_capacity_bytes, protected_reserve_bytes,"
            " initial_nonqueue_bytes, reserve_enforcement, storage_admission_policy,"
            " reclaim_granularity, release_trigger, delivery_assumption,"
            " overlap_objective_revision, tie_break_profile_revision, event_order_revision,"
            " time_quantization_revision, display_format_revision, semantic_hash, published_at_us"
            ") VALUES (?, ?, ?, 'DRAFT', ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,"
            " ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                revision_id,
                scenario_id,
                revision_no,
                snapshot.schema_version,
                snapshot.decision_question[:1000],
                snapshot.analysis_window.start.microseconds,
                snapshot.analysis_window.end.microseconds,
                snapshot.analysis_mode.value,
                ContactSource.SYNTHETIC_INJECTED.value,
                snapshot.source_revision_id[:96],
                graph.policy_key,
                graph.spacecraft_key,
                storage.mode.value,
                _exact(storage.physical_capacity_bytes) if enabled else None,
                _exact(storage.reserve_bytes) if enabled else None,
                _exact(storage.initial_occupancy_bytes) if enabled else None,
                storage.reserve_enforcement.value if storage.reserve_enforcement else None,
                storage.admission_policy.value if storage.admission_policy else None,
                storage.reclaim_granularity.value if storage.reclaim_granularity else None,
                storage.release_trigger.value if storage.release_trigger else None,
                storage.delivery_assumption.value if storage.delivery_assumption else None,
                manifest["overlap_objective_revision"],
                manifest["tie_break_profile_revision"],
                manifest["event_order_revision"],
                manifest["time_quantization_revision"],
                manifest["display_format_revision"],
                revision_hash,
                self._now_us(),
            ),
        )
        station_ids = self._write_stations(connection, revision_id, graph, snapshot)
        payload_ids = self._write_payloads(connection, revision_id, graph, snapshot)
        for predecessor, successor, kind in graph.dependencies:
            connection.execute(
                "INSERT INTO payload_dependency (scenario_revision_id, predecessor_payload_id,"
                " successor_payload_id, dependency_kind) VALUES (?, ?, ?, ?)",
                (revision_id, payload_ids[predecessor], payload_ids[successor], kind),
            )
        connection.execute(
            "UPDATE scenario_revision SET lifecycle_status = 'PUBLISHED' WHERE id = ?",
            (revision_id,),
        )
        return revision_id, station_ids, payload_ids

    def _write_stations(
        self,
        connection: sqlite3.Connection,
        revision_id: str,
        graph: Any,
        snapshot: ScenarioSnapshot,
    ) -> dict[str, str]:
        capacity_by_key = {station.stable_key: station.capacity for station in snapshot.stations}
        communication_payloads = {
            spec.stable_key: spec.payload
            for spec in graph.profiles
            if spec.kind.value == "COMMUNICATION"
        }
        station_ids: dict[str, str] = {}
        for station in graph.stations:
            station_id = str(uuid4())
            station_ids[station.stable_key] = station_id
            connection.execute(
                "INSERT INTO scenario_station (id, scenario_revision_id, stable_key,"
                " station_preference_rank, minimum_elevation_udeg, link_compatibility,"
                " contact_source, communication_key, ground_station_key)"
                " VALUES (?, ?, ?, ?, ?, 'UNKNOWN', ?, ?, ?)",
                (
                    station_id,
                    revision_id,
                    station.stable_key,
                    station.preference_rank,
                    station.minimum_elevation_udeg,
                    ContactSource.SYNTHETIC_INJECTED.value,
                    station.communication_key,
                    station.ground_station_key,
                ),
            )
            self._write_communication(
                connection,
                revision_id,
                station.stable_key,
                communication_payloads[station.communication_key],
                capacity_by_key[station.stable_key],
            )
        return station_ids

    def _write_communication(
        self,
        connection: sqlite3.Connection,
        revision_id: str,
        station_key: str,
        payload: Mapping[str, Any],
        capacity: Any,
    ) -> None:
        communication_id = str(uuid4())
        connection.execute(
            "INSERT INTO communication_revision (id, scenario_revision_id, stable_key,"
            " provider_kind, fixed_capacity_bytes, rate_semantics, measurement_point, rate_scope,"
            " accounted_effects, acquisition_guard_us, release_guard_us, reserve_kind,"
            " reserve_bytes, capacity_accounting_layer, rate_unknown, evidence_state,"
            " source_revision_id, rationale)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                communication_id,
                revision_id,
                station_key,
                payload["provider_kind"],
                _exact(payload["fixed_capacity_bytes"]),
                payload["rate_semantics"],
                payload["measurement_point"],
                payload["rate_scope"],
                ",".join(sorted(payload["accounted_effects"])),
                payload["acquisition_guard_us"],
                payload["release_guard_us"],
                payload["reserve_kind"],
                _exact(payload["reserve_bytes"]),
                payload["capacity_accounting_layer"],
                1 if payload["rate_unknown"] else 0,
                payload["evidence_state"],
                payload["source_revision_id"],
                payload["rationale"],
            ),
        )
        for segment in payload["timeline_segments"]:
            connection.execute(
                "INSERT INTO communication_timeline_segment (communication_revision_id,"
                " segment_kind, ordinal, start_offset_us, end_offset_us, rate_numerator_bits,"
                " rate_denominator_seconds) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    communication_id,
                    segment["segment_kind"],
                    segment["ordinal"],
                    segment["start_offset_us"],
                    segment["end_offset_us"],
                    _exact(segment["rate_numerator_bits"]),
                    _exact(segment["rate_denominator_seconds"]),
                ),
            )
        assert capacity is not None  # the decomposition and the snapshot agree by construction

    def _write_payloads(
        self,
        connection: sqlite3.Connection,
        revision_id: str,
        graph: Any,
        snapshot: ScenarioSnapshot,
    ) -> dict[str, str]:
        by_key = {payload.stable_key: payload for payload in snapshot.payloads}
        payload_ids: dict[str, str] = {}
        for spec in graph.payloads:
            payload_id = str(uuid4())
            payload_ids[spec.stable_key] = payload_id
            domain_payload = by_key[spec.stable_key]
            connection.execute(
                "INSERT INTO scenario_payload (id, scenario_revision_id, stable_key,"
                " payload_type_key, display_name, media_type, producer_kind, ready_at_us,"
                " logical_size_bytes, storage_footprint_bytes, service_class, mission_priority,"
                " queue_sequence, deadline_at_us, deadline_target, post_deadline_action,"
                " expiry_at_us, severity_rank, segmentation, chunk_size_bytes, resume_supported,"
                " bundle_key, bundle_member_role, initial_storage_state)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    payload_id,
                    revision_id,
                    spec.stable_key,
                    spec.payload_type_key,
                    spec.row["display_name"][:160],
                    domain_payload.media_type,
                    spec.row["producer_kind"],
                    _us(spec.row["ready_at"]),
                    _exact(spec.row["logical_size_bytes"]),
                    _exact(spec.row["storage_footprint_bytes"]),
                    spec.row["service_class"],
                    spec.row["mission_priority"],
                    spec.row["queue_sequence"],
                    _us(spec.row["deadline_at"]),
                    spec.row["deadline_target"],
                    spec.row["post_deadline_action"],
                    _us(spec.row["expiry_at"]),
                    spec.row["severity_rank"],
                    domain_payload.segmentation.value,
                    _exact(domain_payload.chunk_size_bytes),
                    1 if domain_payload.resume_supported else 0,
                    spec.row["bundle_key"],
                    spec.row["bundle_member_role"],
                    spec.row["initial_storage_state"],
                ),
            )
        return payload_ids

    @staticmethod
    def _keys(connection: sqlite3.Connection, table: str, revision_id: str) -> dict[str, str]:
        # `table` is one of two literals chosen by the caller, never user input.
        statement = {
            "scenario_station": "SELECT stable_key, id FROM scenario_station "
            "WHERE scenario_revision_id = ?",
            "scenario_payload": "SELECT stable_key, id FROM scenario_payload "
            "WHERE scenario_revision_id = ?",
        }[table]
        return {
            str(row["stable_key"]): str(row["id"])
            for row in connection.execute(statement, (revision_id,)).fetchall()
        }

    def _ensure_snapshot(
        self, connection: sqlite3.Connection, run: StoredRun, revision_id: str
    ) -> str:
        existing = connection.execute(
            "SELECT id FROM input_snapshot WHERE content_sha256 = ? "
            "AND canonicalization_revision = ?",
            (run.input_snapshot_hash, CANONICALIZATION_REVISION),
        ).fetchone()
        if existing is not None:
            return str(existing["id"])
        snapshot_id = str(uuid4())
        payload = run.input_snapshot_payload or {}
        assert run.snapshot is not None
        connection.execute(
            "INSERT INTO input_snapshot (id, scenario_revision_id, schema_version,"
            " json_schema_id, canonicalization_revision, canonical_payload, canonical_bytes,"
            " content_sha256, validation_status, validation_code, created_at_us)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'VALID', NULL, ?)",
            (
                snapshot_id,
                revision_id,
                run.snapshot.schema_version,
                JSON_SCHEMA_ID,
                CANONICALIZATION_REVISION,
                json.dumps(payload, ensure_ascii=False, sort_keys=True, default=str),
                canonical_bytes(payload),
                run.input_snapshot_hash,
                self._now_us(),
            ),
        )
        return snapshot_id

    def _ensure_manifest(self, connection: sqlite3.Connection, manifest: Mapping[str, Any]) -> str:
        stable_key = f"{manifest['engine_version']}/{manifest['code_revision']}"
        existing = connection.execute(
            "SELECT id FROM engine_manifest WHERE stable_key = ?", (stable_key,)
        ).fetchone()
        if existing is not None:
            return str(existing["id"])
        import hashlib

        manifest_id = str(uuid4())
        connection.execute(
            "INSERT INTO engine_manifest (id, stable_key, engine_version, code_revision,"
            " orbit_provider_revision, capacity_engine_revision, scheduler_revision,"
            " storage_reducer_revision, constants_revision, time_reference_revision,"
            " frame_transform_revision, event_solver_revision, canonicalization_revision,"
            " manifest_sha256) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                manifest_id,
                stable_key,
                manifest["engine_version"],
                manifest["code_revision"],
                manifest["orbit_provider_revision"],
                manifest["capacity_engine_revision"],
                manifest["scheduler_revision"],
                manifest["storage_reducer_revision"],
                manifest["constants_revision"],
                manifest["time_reference_revision"],
                manifest["frame_transform_revision"],
                manifest["event_solver_revision"],
                manifest["canonicalization_revision"],
                hashlib.sha256(canonical_bytes(dict(manifest))).hexdigest(),
            ),
        )
        return manifest_id

    def _write_run(
        self,
        connection: sqlite3.Connection,
        run: StoredRun,
        snapshot_id: str,
        manifest_id: str,
        station_ids: dict[str, str],
        payload_ids: dict[str, str],
    ) -> None:
        now = self._now_us()
        connection.execute(
            "INSERT INTO scenario_run (id, input_snapshot_id, engine_manifest_id,"
            " replay_of_run_id, status, retention_class, requested_at_us, started_at_us,"
            " finished_at_us, terminal_stage_code, error_code, result_content_hash,"
            " run_record_hash) VALUES (?, ?, ?, NULL, ?, 'STANDARD', ?, ?, ?, ?, NULL, ?, ?)",
            (
                run.run_id,
                snapshot_id,
                manifest_id,
                run.status,
                now,
                now,
                now,
                run.stages[-1]["stage_code"],
                run.result_content_hash,
                run.run_record_hash,
            ),
        )
        for stage in run.stages:
            connection.execute(
                "INSERT INTO run_stage (id, run_id, stage_code, stage_ordinal, status,"
                " produced_row_count, error_code) VALUES (?, ?, ?, ?, ?, ?, NULL)",
                (
                    str(uuid4()),
                    run.run_id,
                    stage["stage_code"],
                    stage["stage_ordinal"],
                    stage["status"],
                    stage["row_count"],
                ),
            )
        self._write_results(
            connection, run.run_id, result_rows(run.result), station_ids, payload_ids
        )
        # Immutable rendered artifact alongside the typed rows, so a restarted process can serve
        # the result document without recomputing. The typed rows remain the relational record.
        connection.execute(
            "INSERT INTO run_result_document (run_id, canonicalization_revision,"
            " content_sha256, document) VALUES (?, ?, ?, ?)",
            (
                run.run_id,
                CANONICALIZATION_REVISION,
                run.result_content_hash,
                json.dumps(run.result, ensure_ascii=False, sort_keys=True),
            ),
        )

    def _write_results(
        self,
        connection: sqlite3.Connection,
        run_id: str,
        rows: PersistedRows,
        station_ids: dict[str, str],
        payload_ids: dict[str, str],
    ) -> None:
        result_ids: dict[str, str] = {}
        for row in rows.results:
            result_id = str(uuid4())
            result_ids[str(row["stable_key"])] = result_id
            connection.execute(
                "INSERT INTO run_result (id, run_id, stable_key, result_kind,"
                " calculation_status, decision_grade) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    result_id,
                    run_id,
                    row["stable_key"],
                    row["result_kind"],
                    row["calculation_status"],
                    row["decision_grade"],
                ),
            )
        for row in rows.geometric:
            connection.execute(
                "INSERT INTO geometric_access (result_id, scenario_station_id, true_aos_us,"
                " true_los_us, clipped_start_us, clipped_end_us, maximum_elevation_udeg,"
                " maximum_elevation_at_us, contact_source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    station_ids[str(row["station_key"])],
                    _us(row["true_aos"]),
                    _us(row["true_los"]),
                    _us(row["clipped_start"]),
                    _us(row["clipped_end"]),
                    row["maximum_elevation_udeg"],
                    _us(row["maximum_elevation_at"]),
                    row["contact_source"],
                ),
            )
        for row in rows.modeled:
            connection.execute(
                "INSERT INTO modeled_contact (result_id, geometric_result_id, link_compatibility,"
                " usable_start_us, usable_end_us, primary_reason_code) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    result_ids[str(row["geometric_stable_key"])],
                    row["link_compatibility"],
                    _us(row["usable_start"]),
                    _us(row["usable_end"]),
                    row["primary_reason_code"],
                ),
            )
        for row in rows.candidates:
            connection.execute(
                "INSERT INTO candidate_session (result_id, modeled_contact_result_id,"
                " capacity_bytes, conflict_component_key) VALUES (?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    result_ids[str(row["modeled_stable_key"])],
                    _exact(row["capacity_bytes"]),
                    row["conflict_component_key"],
                ),
            )
        for row in rows.scheduled:
            connection.execute(
                "INSERT INTO scheduled_session (result_id, candidate_result_id,"
                " selection_ordinal, primary_reason_code) VALUES (?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    result_ids[str(row["candidate_stable_key"])],
                    row["selection_ordinal"],
                    row["primary_reason_code"],
                ),
            )
        for row in rows.allocations:
            connection.execute(
                "INSERT INTO transfer_allocation (result_id, scheduled_session_result_id,"
                " scenario_payload_id, allocation_ordinal, logical_offset_start, logical_bytes,"
                " started_at_us, ended_at_us, modeled_progress_after_bytes,"
                " modeled_tx_complete_at_us, deadline_status, remaining_after_bytes,"
                " primary_reason_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    result_ids[str(row["scheduled_session_stable_key"])],
                    payload_ids[str(row["payload_key"])],
                    row["allocation_ordinal"],
                    _exact(row["logical_offset_start"]),
                    _exact(row["logical_bytes"]),
                    _us(row["started_at"]),
                    _us(row["ended_at"]),
                    _exact(row["modeled_progress_after_bytes"]),
                    _us(row["modeled_tx_complete_at"]),
                    row["deadline_status"],
                    _exact(row["remaining_after_bytes"]),
                    row["primary_reason_code"],
                ),
            )
        for row in rows.events:
            allocation_key = row["allocation_stable_key"]
            connection.execute(
                "INSERT INTO run_event (result_id, run_id, event_at_us, event_order,"
                " event_domain, event_kind, scenario_payload_id, allocation_result_id,"
                " delta_logical_bytes, remaining_logical_bytes, delta_storage_bytes,"
                " occupancy_bytes, reserve_breach_bytes, rejected_bytes, reason_code)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    run_id,
                    _us(row["event_at"]),
                    row["event_order"],
                    row["event_domain"],
                    row["event_kind"],
                    payload_ids.get(str(row["payload_key"])) if row["payload_key"] else None,
                    result_ids.get(str(allocation_key)) if allocation_key else None,
                    _exact(row["delta_logical_bytes"]),
                    _exact(row["remaining_logical_bytes"]),
                    _exact(row["delta_storage_bytes"]),
                    _exact(row["occupancy_bytes"]),
                    _exact(row["reserve_breach_bytes"]),
                    _exact(row["rejected_bytes"]),
                    row["reason_code"],
                ),
            )
        for row in rows.metrics:
            connection.execute(
                "INSERT INTO run_metric (result_id, metric_code, scope_code,"
                " scenario_station_id, scenario_payload_id, unit_code, definition_revision,"
                " accounting_layer, value_integer) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    result_ids[str(row["stable_key"])],
                    row["metric_code"],
                    row["scope_code"],
                    station_ids.get(str(row["station_key"])) if row["station_key"] else None,
                    payload_ids.get(str(row["payload_key"])) if row["payload_key"] else None,
                    row["unit_code"],
                    row["definition_revision"],
                    row["accounting_layer"],
                    _exact(row["value_integer"]),
                ),
            )
        for row in rows.annotations:
            subject = row["subject_stable_key"]
            connection.execute(
                "INSERT INTO run_annotation (result_id, subject_result_id, annotation_kind,"
                " code, severity, ordinal, rule_revision, compared_result_id, criterion_code,"
                " criterion_value_integer, criterion_value_text, unit_code, message)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, NULL, ?, NULL, ?, NULL, NULL)",
                (
                    result_ids[str(row["stable_key"])],
                    result_ids.get(str(subject)) if subject else None,
                    row["annotation_kind"],
                    row["code"],
                    row["severity"],
                    row["ordinal"],
                    row["rule_revision"],
                    row["criterion_code"],
                    row["criterion_value_text"],
                ),
            )

    # ------------------------------------------------------------------ reading

    def get(self, run_id: str) -> StoredRun | None:
        with _redacted("load run"), self._connection() as connection:
            row = connection.execute(
                "SELECT r.status, r.result_content_hash, r.run_record_hash, s.content_sha256"
                " FROM scenario_run r JOIN input_snapshot s ON s.id = r.input_snapshot_id"
                " WHERE r.id = ?",
                (run_id,),
            ).fetchone()
            if row is None:
                return None
            stages = tuple(
                {
                    "stage_code": str(stage["stage_code"]),
                    "stage_ordinal": int(stage["stage_ordinal"]),
                    "status": str(stage["status"]),
                    "row_count": int(stage["produced_row_count"]),
                }
                for stage in connection.execute(
                    "SELECT stage_code, stage_ordinal, status, produced_row_count FROM run_stage"
                    " WHERE run_id = ? ORDER BY stage_ordinal",
                    (run_id,),
                ).fetchall()
            )
            return StoredRun(
                run_id=run_id,
                status=str(row["status"]),
                input_snapshot_hash=str(row["content_sha256"]),
                result_content_hash=str(row["result_content_hash"]),
                run_record_hash=str(row["run_record_hash"]),
                stages=stages,
                result=self._read_document(connection, run_id, str(row["result_content_hash"])),
                persisted_rows=self._read_rows(connection, run_id),
            )

    @staticmethod
    def _read_document(
        connection: sqlite3.Connection, run_id: str, expected_hash: str
    ) -> dict[str, Any]:
        row = connection.execute(
            "SELECT content_sha256, document FROM run_result_document WHERE run_id = ?",
            (run_id,),
        ).fetchone()
        if row is None:  # pragma: no cover - every stored run writes its document
            return {}
        if str(row["content_sha256"]) != expected_hash:
            raise SqlitePersistenceError(
                "the stored result document does not match the run's result content hash"
            )
        loaded: dict[str, Any] = json.loads(str(row["document"]))
        return loaded

    def _read_rows(self, connection: sqlite3.Connection, run_id: str) -> PersistedRows:
        results = connection.execute(
            "SELECT id, stable_key, result_kind, calculation_status, decision_grade"
            " FROM run_result WHERE run_id = ?",
            (run_id,),
        ).fetchall()
        key_of = {str(row["id"]): str(row["stable_key"]) for row in results}
        station_key = self._lookup(connection, "scenario_station")
        payload_key = self._lookup(connection, "scenario_payload")

        def fetch(statement: str) -> Sequence[sqlite3.Row]:
            return connection.execute(statement, (run_id,)).fetchall()

        geometric = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "station_key": station_key[str(row["scenario_station_id"])],
                "true_aos": _iso(row["true_aos_us"]),
                "true_los": _iso(row["true_los_us"]),
                "clipped_start": _iso(row["clipped_start_us"]),
                "clipped_end": _iso(row["clipped_end_us"]),
                "maximum_elevation_udeg": _int(row["maximum_elevation_udeg"]),
                "maximum_elevation_at": _iso(row["maximum_elevation_at_us"]),
                "contact_source": str(row["contact_source"]),
            }
            for row in fetch(
                "SELECT g.* FROM geometric_access g JOIN run_result r ON r.id = g.result_id"
                " WHERE r.run_id = ?"
            )
        )
        modeled = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "geometric_stable_key": key_of[str(row["geometric_result_id"])],
                "link_compatibility": str(row["link_compatibility"]),
                "usable_start": _iso(row["usable_start_us"]),
                "usable_end": _iso(row["usable_end_us"]),
                "primary_reason_code": row["primary_reason_code"],
            }
            for row in fetch(
                "SELECT m.* FROM modeled_contact m JOIN run_result r ON r.id = m.result_id"
                " WHERE r.run_id = ?"
            )
        )
        candidates = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "modeled_stable_key": key_of[str(row["modeled_contact_result_id"])],
                "capacity_bytes": _int(row["capacity_bytes"]),
                "conflict_component_key": row["conflict_component_key"],
            }
            for row in fetch(
                "SELECT c.* FROM candidate_session c JOIN run_result r ON r.id = c.result_id"
                " WHERE r.run_id = ?"
            )
        )
        scheduled = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "candidate_stable_key": key_of[str(row["candidate_result_id"])],
                "selection_ordinal": int(row["selection_ordinal"]),
                "primary_reason_code": str(row["primary_reason_code"]),
            }
            for row in fetch(
                "SELECT s.* FROM scheduled_session s JOIN run_result r ON r.id = s.result_id"
                " WHERE r.run_id = ?"
            )
        )
        allocations = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "scheduled_session_stable_key": key_of[str(row["scheduled_session_result_id"])],
                "payload_key": payload_key[str(row["scenario_payload_id"])],
                "allocation_ordinal": int(row["allocation_ordinal"]),
                "logical_offset_start": int(row["logical_offset_start"]),
                "logical_bytes": int(row["logical_bytes"]),
                "started_at": _iso(row["started_at_us"]),
                "ended_at": _iso(row["ended_at_us"]),
                "modeled_progress_after_bytes": int(row["modeled_progress_after_bytes"]),
                "modeled_tx_complete_at": _iso(row["modeled_tx_complete_at_us"]),
                "deadline_status": row["deadline_status"],
                "remaining_after_bytes": int(row["remaining_after_bytes"]),
                "primary_reason_code": str(row["primary_reason_code"]),
            }
            for row in fetch(
                "SELECT t.* FROM transfer_allocation t JOIN run_result r ON r.id = t.result_id"
                " WHERE r.run_id = ?"
            )
        )
        events = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "event_at": _iso(row["event_at_us"]),
                "event_order": int(row["event_order"]),
                "event_domain": str(row["event_domain"]),
                "event_kind": str(row["event_kind"]),
                "payload_key": (
                    payload_key[str(row["scenario_payload_id"])]
                    if row["scenario_payload_id"]
                    else None
                ),
                "allocation_stable_key": (
                    key_of[str(row["allocation_result_id"])]
                    if row["allocation_result_id"]
                    else None
                ),
                "delta_logical_bytes": _int(row["delta_logical_bytes"]),
                "remaining_logical_bytes": _int(row["remaining_logical_bytes"]),
                "delta_storage_bytes": _int(row["delta_storage_bytes"]),
                "occupancy_bytes": _int(row["occupancy_bytes"]),
                "reserve_breach_bytes": _int(row["reserve_breach_bytes"]),
                "rejected_bytes": _int(row["rejected_bytes"]),
                "reason_code": str(row["reason_code"]),
            }
            for row in fetch("SELECT * FROM run_event WHERE run_id = ?")
        )
        metrics = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "metric_code": str(row["metric_code"]),
                "scope_code": str(row["scope_code"]),
                "station_key": (
                    station_key[str(row["scenario_station_id"])]
                    if row["scenario_station_id"]
                    else None
                ),
                "payload_key": (
                    payload_key[str(row["scenario_payload_id"])]
                    if row["scenario_payload_id"]
                    else None
                ),
                "unit_code": str(row["unit_code"]),
                "definition_revision": str(row["definition_revision"]),
                "accounting_layer": row["accounting_layer"],
                "value_integer": _int(row["value_integer"]),
            }
            for row in fetch(
                "SELECT m.* FROM run_metric m JOIN run_result r ON r.id = m.result_id"
                " WHERE r.run_id = ?"
            )
        )
        annotations = tuple(
            {
                "stable_key": key_of[str(row["result_id"])],
                "subject_stable_key": (
                    key_of[str(row["subject_result_id"])] if row["subject_result_id"] else None
                ),
                "annotation_kind": str(row["annotation_kind"]),
                "code": str(row["code"]),
                "severity": str(row["severity"]),
                "ordinal": int(row["ordinal"]),
                "rule_revision": str(row["rule_revision"]),
                "criterion_code": row["criterion_code"],
                "criterion_value_text": row["criterion_value_text"],
            }
            for row in fetch(
                "SELECT a.* FROM run_annotation a JOIN run_result r ON r.id = a.result_id"
                " WHERE r.run_id = ?"
            )
        )
        return PersistedRows(
            results=tuple(
                {
                    "stable_key": str(row["stable_key"]),
                    "result_kind": str(row["result_kind"]),
                    "calculation_status": str(row["calculation_status"]),
                    "decision_grade": (
                        str(row["decision_grade"]) if row["decision_grade"] is not None else None
                    ),
                }
                for row in results
            ),
            geometric=geometric,
            modeled=modeled,
            candidates=candidates,
            scheduled=scheduled,
            allocations=allocations,
            events=events,
            metrics=metrics,
            annotations=annotations,
        )

    @staticmethod
    def _lookup(connection: sqlite3.Connection, table: str) -> dict[str, str]:
        statement = {
            "scenario_station": "SELECT id, stable_key FROM scenario_station",
            "scenario_payload": "SELECT id, stable_key FROM scenario_payload",
        }[table]
        return {
            str(row["id"]): str(row["stable_key"])
            for row in connection.execute(statement).fetchall()
        }

    # ------------------------------------------------------------------ helpers

    @staticmethod
    def _now_us() -> int:
        delta = datetime.now(UTC) - EPOCH
        return (delta.days * 86_400 + delta.seconds) * 1_000_000 + delta.microseconds

    @staticmethod
    def _manifest() -> Mapping[str, Any]:
        from semantix_passbudget.application.service import ENGINE_MANIFEST

        return ENGINE_MANIFEST

    def _revision_hash(self, snapshot: ScenarioSnapshot, graph: Any) -> str:
        import hashlib

        return hashlib.sha256(
            canonical_bytes(
                {
                    "scenario": snapshot.fixture_id,
                    "window": snapshot.analysis_window.start.isoformat()
                    + "/"
                    + snapshot.analysis_window.end.isoformat(),
                    "mode": snapshot.analysis_mode.value,
                    "stations": [item.stable_key for item in graph.stations],
                    "payloads": [item.stable_key for item in graph.payloads],
                    "decision_question": snapshot.decision_question,
                }
            )
        ).hexdigest()
